import Link from "@/components/ui/SiteLink";

export default function Logo({ variant = "dark" }) {
  return (
    <Link href="/" className="brand gap-3 inline-flex items-center text-inherit relative z-[3] [.ft-brand_&]:text-white [.site-header_&:is(a,_button):focus-visible]:rounded-[3px] [.site-header_&:is(a,_button):focus-visible]:outline-[length:2px] [.site-header_&:is(a,_button):focus-visible]:outline [.site-header_&:is(a,_button):focus-visible]:outline-[color:var(--nav-focus)] [.site-header_&:is(a,_button):focus-visible]:outline-offset-[5px] [.site-header_&]:gap-3.5 [.site-header_&]:items-center [.site-header_&]:[transition:color_0.45s_ease] [.site-header_&]:[&&]:text-[color:var(--nav-fg)] [.footer.ft_&:is(a,_button):focus-visible]:rounded-[3px] [.footer.ft_&:is(a,_button):focus-visible]:outline-[length:2px] [.footer.ft_&:is(a,_button):focus-visible]:outline [.footer.ft_&:is(a,_button):focus-visible]:outline-[color:#fff] [.footer.ft_&:is(a,_button):focus-visible]:outline-offset-[4px] [.footer.ft_.ft-brand_&]:gap-3.5 [.footer.ft_.ft-brand_&]:text-[color:var(--ft-ink)]" aria-label="Aspen Pharmaceuticals home">
      <img className="px-2 py-[7px] rounded-[11px] block box-border h-[46px] w-auto [background:#fff] max-[600px]:px-[7px] max-[600px]:py-1.5 max-[600px]:rounded-[9px] max-[600px]:h-10 [.ft-brand_.brand_&]:px-[9px] [.ft-brand_.brand_&]:py-2 [.ft-brand_.brand_&]:h-[52px] [.site-header_.brand_&]:w-auto [.site-header_.brand_&]:[&&]:px-1 [.site-header_.brand_&]:[&&]:py-[5px] [.site-header_.brand_&]:[&&]:h-11 max-[1200px]:[.site-header_.brand_&]:[&&]:h-9 max-[600px]:[.site-header_.brand_&]:[&&]:h-[38px] [.footer.ft_.ft-brand_.brand_&]:w-auto [.footer.ft_.ft-brand_.brand_&]:h-12 max-[700px]:[.footer.ft_.ft-brand_.brand_&]:h-11" src="/images/logo.png" alt="" width="189" height="167" />
      <span className="brand-name [font-family:var(--font-brand)] text-[27px] font-semibold tracking-[var(--heading-tracking)] leading-[0.95] [word-spacing:0.06em] max-[900px]:text-[25px] [.site-header_&]:flex [.site-header_&]:flex-col [.site-header_&]:items-start [.site-header_&]:font-semibold [.site-header_&]:text-[28px] [.site-header_&]:leading-none [.site-header_&]:font-body [.site-header_&]:tracking-[-0.012em] [.site-header_&]:normal-case [.site-header_&]:text-inherit max-[1200px]:[.site-header_&]:text-[23px] [.footer.ft_.ft-brand_&]:flex [.footer.ft_.ft-brand_&]:flex-col [.footer.ft_.ft-brand_&]:items-start [.footer.ft_.ft-brand_&]:font-semibold [.footer.ft_.ft-brand_&]:text-[28px] [.footer.ft_.ft-brand_&]:leading-none [.footer.ft_.ft-brand_&]:font-body [.footer.ft_.ft-brand_&]:tracking-[-0.012em] [.footer.ft_.ft-brand_&]:text-[color:var(--ft-ink)] max-[700px]:[.footer.ft_.ft-brand_&]:text-[25px]">
        Aspen <strong className="block uppercase mt-[5px] font-body text-[13px] font-normal tracking-[0.32em] opacity-[0.6] [.site-header_.brand-name_&]:block [.site-header_.brand-name_&]:mt-[7px] [.site-header_.brand-name_&]:font-medium [.site-header_.brand-name_&]:text-[10px] [.site-header_.brand-name_&]:leading-none [.site-header_.brand-name_&]:font-body [.site-header_.brand-name_&]:tracking-[0.3em] [.site-header_.brand-name_&]:uppercase [.site-header_.brand-name_&]:opacity-[0.8] [.site-header_.brand-name_&]:text-inherit max-[1200px]:[.site-header_.brand-name_&]:mt-1.5 max-[1200px]:[.site-header_.brand-name_&]:text-[8.5px] max-[1200px]:[.site-header_.brand-name_&]:tracking-[0.28em] [.footer.ft_.ft-brand_.brand-name_&]:block [.footer.ft_.ft-brand_.brand-name_&]:mt-[7px] [.footer.ft_.ft-brand_.brand-name_&]:font-medium [.footer.ft_.ft-brand_.brand-name_&]:text-[10px] [.footer.ft_.ft-brand_.brand-name_&]:leading-none [.footer.ft_.ft-brand_.brand-name_&]:font-body [.footer.ft_.ft-brand_.brand-name_&]:tracking-[0.3em] [.footer.ft_.ft-brand_.brand-name_&]:uppercase [.footer.ft_.ft-brand_.brand-name_&]:opacity-[0.8] [.footer.ft_.ft-brand_.brand-name_&]:text-inherit">Pharmaceuticals</strong>
      </span>
    </Link>
  );
}
