export default function RfHeading({ eyebrow, title, copy }) {
  return (
    <div className="rf-heading max-w-[720px] [.rf-sustain_&]:mb-0 [.rn-approach_&]:[&&]:mb-0">
      <span className="block mb-[22px] text-[color:var(--rf-teal-text)] uppercase !text-[14px] !font-bold !tracking-[0.12em] [.rf-sustain_&]:[&&]:text-red-on-dark [.rf-sustain_&]:[&&&&]:mb-[18px] [.rf-quality_&]:text-red-on-dark [.rf-quality_&]:[&&]:mb-[18px] [.rf-about_&]:mb-[18px] [.rf-reach_&]:[&&&]:mb-[18px] [body:has(.hv)_&]:[&&&]:font-body [.ab-values_&]:[&&&]:text-red [.ab-values_&]:leading-[1.4] [.ab-values_&]:font-body [.mf-stages_&]:[&&]:leading-[1.4] [.mf-stages_&]:[&&]:font-body [.mf-stages_&]:[&&&&]:text-red [.rn-approach_&]:[&&&&&]:text-red [.rn-approach_&]:[&&&]:leading-[1.4] [.rn-approach_&]:[&&&]:font-body">{eyebrow}</span>
      <h2 className="m-0 text-[color:var(--rf-ink)] font-semibold text-[length:var(--fs-section-title)] leading-[var(--heading-leading)] font-heading tracking-[var(--heading-tracking)] [word-spacing:0.06em] [.rf-quality_.rf-heading_&]:[&&&]:text-white [.rf-quality_.rf-heading_&]:[&&&]:font-semibold [.rf-quality_.rf-heading_&]:[&&&]:text-[length:clamp(30px,3.2vw,40px)] [.rf-quality_.rf-heading_&]:[&&&]:leading-[1.2] [.rf-quality_.rf-heading_&]:[&&&]:font-body [.rf-quality_.rf-heading_&]:[&&&]:tracking-[-0.012em] [.rf-sustain_.rf-heading_&]:[&&&&&]:text-white [.rf-sustain_.rf-heading_&]:[&&&&&]:font-semibold [.rf-sustain_.rf-heading_&]:[&&&&&]:text-[length:clamp(30px,3.2vw,40px)] [.rf-sustain_.rf-heading_&]:[&&&&&]:leading-[1.2] [.rf-sustain_.rf-heading_&]:[&&&&&]:font-body [.rf-sustain_.rf-heading_&]:[&&&&&]:tracking-[-0.012em] [.rf-about_.rf-heading_&]:[&&]:font-semibold [.rf-about_.rf-heading_&]:[&&]:text-[length:clamp(30px,3.2vw,40px)] [.rf-about_.rf-heading_&]:[&&]:leading-[1.2] [.rf-about_.rf-heading_&]:[&&]:font-body [.rf-about_.rf-heading_&]:[&&]:tracking-[-0.012em] [.rf-about_.rf-heading_&]:[&&]:text-navy [.rf-reach_.rf-heading_&]:[&&&&]:font-semibold [.rf-reach_.rf-heading_&]:[&&&&]:text-[length:clamp(30px,3.2vw,40px)] [.rf-reach_.rf-heading_&]:[&&&&]:leading-[1.2] [.rf-reach_.rf-heading_&]:[&&&&]:font-body [.rf-reach_.rf-heading_&]:[&&&&]:tracking-[-0.012em] [.rf-reach_.rf-heading_&]:[&&&&]:text-navy [.ab-values_.rf-heading_&]:[&&&&&&]:font-semibold [.ab-values_.rf-heading_&]:[&&&&&&]:text-[length:clamp(30px,3.2vw,40px)] [.ab-values_.rf-heading_&]:[&&&&&&]:leading-[1.2] [.ab-values_.rf-heading_&]:[&&&&&&]:font-body [.ab-values_.rf-heading_&]:[&&&&&&]:tracking-[-0.012em] [.ab-values_.rf-heading_&]:[&&&&&&]:text-navy [.mf-stages_&]:font-semibold [.mf-stages_&]:text-[length:clamp(30px,3.2vw,40px)] [.mf-stages_&]:leading-[1.2] [.mf-stages_&]:font-body [.mf-stages_&]:tracking-[-0.012em] [.mf-stages_&]:text-navy [.rn-approach_&]:mx-0 [.rn-approach_&]:mt-3.5 [.rn-approach_&]:mb-0 [.rn-approach_&]:[&&]:font-semibold [.rn-approach_&]:[&&]:text-[length:clamp(30px,3.2vw,40px)] [.rn-approach_&]:[&&]:leading-[1.2] [.rn-approach_&]:[&&]:font-body [.rn-approach_&]:[&&]:tracking-[-0.012em] [.rn-approach_&]:[&&]:text-navy">{title}</h2>
      {copy && <p className="mx-0 mt-[22px] mb-0 text-[color:var(--rf-muted)] text-[16.5px] leading-[1.7]">{copy}</p>}
    </div>
  );
}
